### ISSUE TITLE
Renovação do domínio phppr.org

### ISSUE THREAD

**Issue by nandomoreirame** [phppr/theme-phppr.org#6]
Olá PHP Developers do Paraná!

O nosso domínio [phppr.org](https://phppr.org) esgotou o prazo de 1 ano no dia 31/12/2018, o valor de renovação é de R$60 táokeis... então temos que renová-lo! #goPHPPR #go2019

Estou abrindo essa issue para fazer valer a comunidade, dividindo o valor ficaria bem tranquilo de pagar 😄 

Lembrado que eu manteinho a hospedagem todo mês, e se não conseguir uns trocados para renovar o domínio irei pagar ele também, tranquilão 👍 

Por favor levante as mãos comentando nessa issue quem for ajudar, em 5 dias eu vou contar as cabeças e dividir entre todos.

`/bin/thanks`

**Comment by nillswe** [comment]
Bora nessa! 
Como faço pra ajudar?

**Comment by nandomoreirame** [comment]
Daqui 5 dias eu vou dividir o valor total (R$60) pela quantidade de cabeças que comentarem essa issue com intensão de ajudar 😃 

Se for só nós dois R$30 pra cada, fechado @niltonslf ?

**Comment by MauricioFauth** [comment]
Opa!

**Comment by nandomoreirame** [comment]
@niltonslf @mauriciofauth vou pagar hoje o domínio, dividimos por 3 fica R$20 pra cada?
Usaremos o PicPay, quem não tiver um cadastro pode usar esse [link para fazer um](http://www.picpay.com/convite?@9PTPBW).

Dai podem me pagar pelo link [picpay.me/nandomoreira](https://picpay.me/nandomoreira)

`/bin/thanks`

**Comment by nillswe** [comment]
> @niltonslf @mauriciofauth vou pagar hoje o domínio, dividimos por 3 fica R$20 pra cada?
> Usaremos o PicPay, quem não tiver um cadastro pode usar esse [link para fazer um](http://www.picpay.com/convite?@9PTPBW).
> 
> Dai podem me pagar pelo link [picpay.me/nandomoreira](https://picpay.me/nandomoreira)
> 
> `/bin/thanks`

Não estou conseguindo fazer o pagamento. Está dando como não autorizada.
Vou tentar novamente quando chegar em casa.

**Comment by EvandroSwk** [comment]
Eu posso ajudar também

**Comment by nandomoreirame** [comment]
Ainda não foi pago o boleto galera!

@EvandroSwk podemos dividir em 4 então, ficando R$15 pra cada...

@niltonslf conseguiu usar o PicPay? é um app bem fácil de usar, vc precisa de um cartão de crédido ou adicionar créditos no app por boleto. Essa mensagem "não autorizada" geralmente é do cartão.

@mauriciofauth tudo certo, precisa de ajuda?

Aguardo o retorno de vcs para proceguir.

`/bin/thanks`

**Comment by nillswe** [comment]
> Ainda não foi pago o boleto galera!
> 
> @EvandroSwk podemos dividir em 4 então, ficando R$15 pra cada...
> 
> @niltonslf conseguiu usar o PicPay? é um app bem fácil de usar, vc precisa de um cartão de crédido ou adicionar créditos no app por boleto. Essa mensagem "não autorizada" geralmente é do cartão.
> 
> @mauriciofauth tudo certo, precisa de ajuda?
> 
> Aguardo o retorno de vcs para proceguir.
> 
> `/bin/thanks`

Eu já usei ele algumas vezes. O Problema é que agora só ta dando como transação não autorizada (não sei pq). Olha só: https://photos.app.goo.gl/yy91cfhFGPXf39sr5 
Esse é meu twitter: https://twitter.com/niltonrck
Me manda uma direct lá com sua conta que eu faço uma transferência :) .

**Comment by MauricioFauth** [comment]
@nandomoreirame Tudo certo?

**Comment by nandomoreirame** [comment]
@mauriciofauth eu recebi apenas o seu e o @EvandroSwk 
Ainda não entrei em contato com o @niltonslf então irei pagar com o que temos até o momento 👍

**Comment by straube** [comment]
@nandomoreirame Vi o tweet sobre isso só agora, mas como teve uma baixa te passei R$15,00 no PicPay.

**Comment by nillswe** [comment]
@nandomoreirame, eai mano
To esperando seu contato me passando a conta. Aconteceu alguma coisa com meu picpay que fizeram eles inativar minha conta 👎  
Qualquer coisa me manda um email em niltonrck@gmail.com que eu te passo o help que prometi.

**Comment by nillswe** [comment]
@nandomoreirame, eai mano suave? 
Me confirma se deu certo o recebimento da grana 👍

**Comment by nandomoreirame** [comment]
@niltonslf recebi sim, paguei o boleto hoje inclusive, só semana que vem vai ativar o domíno...
Valeu galera pela ajuda hein, divimos o valor de R$60 em 4 cabeças, ajudou muito \o/
Agora só ano que vem essa bronca! kkk

abraço a todos!

```
/bin/thanks
```
