### ISSUE TITLE
Renovação Domínio para 2020

### ISSUE THREAD

**Issue by flaviosilveira** [phppr/theme-phppr.org#7]
Olá PHP Developers do Paraná!

O nosso domínio phppr.org esgotou o prazo de 1 ano no dia 31/12/2019, o valor de renovação é de R$100... então temos que renová-lo!

Estamos abrindo essa issue para fazer valer a comunidade, cada um colaborando como queira.

Link para colaborar [http://picpay.me/oseunando](http://picpay.me/oseunando).
Fechamos a issue assim que fechar o valor e avisaremos nos grupos.

/bin/thanks

**Comment by MauricioFauth** [comment]
👍

**Comment by straube** [comment]
Feito!

![Screenshot 2019-12-10 at 15 33 37](https://user-images.githubusercontent.com/958870/70557967-afe53300-1b62-11ea-89ba-279aaa64fdf7.png)

**Comment by danielfleck** [comment]
![Screenshot_20191210-160748](https://user-images.githubusercontent.com/3223765/70560422-503d5680-1b67-11ea-929a-6b51b9647459.jpg)

**Comment by flaviosilveira** [comment]
![WhatsApp Image 2019-12-10 at 16 19 58](https://user-images.githubusercontent.com/373688/70561299-f9388100-1b68-11ea-9a8b-80662f9dcc1c.jpeg)

**Comment by flaviosilveira** [comment]
Fechou moçada... 
Tempo recorde.

Sobrou R$4.25.

**Comment by nandomoreirame** [comment]
Boleto pago 🎉 

Obrigado @mauriciofauth @straube @danielfleck e @flaviosilveira 🤘 

![image](https://user-images.githubusercontent.com/1318271/70561663-a1e6e080-1b69-11ea-917f-325993e3ecff.png)
